#!/usr/bin/env node
// Generate js/brand-icons.js from assets/icons/brands/*.svg (Simple Icons, CC0).
// Each file is one <path d="..."> on a 24x24 viewBox; the title is the brand name.
// Usage: node tools/build-icons.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'assets', 'icons', 'brands');
const out = join(root, 'js', 'brand-icons.js');

const icons = {};
for (const file of readdirSync(dir).filter((f) => f.endsWith('.svg')).sort()) {
  const svg = readFileSync(join(dir, file), 'utf8');
  const title = (svg.match(/<title>([^<]*)<\/title>/) || [])[1] || file.replace(/\.svg$/, '');
  const d = (svg.match(/<path[^>]*\sd="([^"]+)"/) || [])[1];
  if (!d) { console.error(`skip ${file}: no <path d=...>`); continue; }
  icons[file.replace(/\.svg$/, '')] = { t: title, d };
}

const body = Object.entries(icons)
  .map(([slug, { t, d }]) => `  ${JSON.stringify(slug)}: { t: ${JSON.stringify(t)}, d: ${JSON.stringify(d)} },`)
  .join('\n');

writeFileSync(out, `// Generated by tools/build-icons.mjs from assets/icons/brands/*.svg.
// Source: Simple Icons (CC0 1.0). Do not edit by hand; add an SVG to the folder and rerun the tool.
// Every path sits on a 24x24 viewBox and is meant to be filled with currentColor.
export const BRAND_ICONS = {
${body}
};
`);
console.log(`wrote ${out}: ${Object.keys(icons).length} icons, ${Math.round(readFileSync(out).length / 1024)} KB`);
